[General]
# Golden Arch — Everforest Sugar Candy

Background="/usr/share/backgrounds/golden-arch/forest-1.jpg"
DimBackgroundImage="0.30"
ScaleImageCropped="true"
ScreenWidth=""
ScreenHeight=""

FullBlur="false"
PartialBlur="true"
BlurRadius="50"

HaveFormBackground="false"
FormPosition="center"

MainColor="#D3C6AA"
AccentColor="#A7C080"
BackgroundColor="#2D353B"
OverrideLoginButtonTextColor="#2D353B"

InterfaceShadowSize="6"
InterfaceShadowOpacity="0.6"

RoundCorners="20"
ScreenPadding="0"
Font="JetBrainsMono Nerd Font"
FontSize="11"
HourFormat="HH:mm"
DateFormat="dddd, d MMMM yyyy"

PasswordFocusColor="#DBBC7F"
PasswordCursorColor="#A7C080"

ForceRightToLeft="false"
ForceLastUser="true"
ForcePasswordFocus="true"
ForceHideCompletePassword="false"
ForceHideVirtualKeyboardButton="true"
ForceHideSystemButtons="false"

TranslatePlaceholderPassword="Password"
TranslateShowPassword="Show password"
TranslateLogin="Sign in"
TranslateLoginFailedWarning="Login failed"
TranslateCapslockWarning="Caps lock is on"
TranslateSession="Session:"
TranslateSuspend="Suspend"
TranslateHibernate="Hibernate"
TranslateReboot="Reboot"
TranslateShutdown="Shutdown"
